#!/usr/bin/env bash

yay -S --noconfirm --needed alacritty
yay -S --noconfirm --needed base
yay -S --noconfirm --needed base-devel
yay -S --noconfirm --needed bash-completion
yay -S --noconfirm --needed bat
yay -S --noconfirm --needed blueman
yay -S --noconfirm --needed brave-bin
yay -S --noconfirm --needed brightnessctl 
yay -S --noconfirm --needed btop
yay -S --noconfirm --needed cava
yay -S --noconfirm --needed clang
yay -S --noconfirm --needed cliphist
yay -S --noconfirm --needed cmake
yay -S --noconfirm --needed cmake-extras
yay -S --noconfirm --needed curl
yay -S --noconfirm --needed dash
yay -S --noconfirm --needed extra-cmake-modules
yay -S --noconfirm --needed eza
yay -S --noconfirm --needed fastfetch
yay -S --noconfirm --needed fcitx5
yay -S --noconfirm --needed fcitx5-qt
yay -S --noconfirm --needed fcitx5-gtk
yay -S --noconfirm --needed fd
yay -S --noconfirm --needed ffmpeg
yay -S --noconfirm --needed ffmpeg4.4
yay -S --noconfirm --needed ffmpegthumbnailer
yay -S --noconfirm --needed file-roller
yay -S --noconfirm --needed firefox
yay -S --noconfirm --needed fwupd
yay -S --noconfirm --needed fzf
yay -S --noconfirm --needed gcc14
yay -S --noconfirm --needed gimp
yay -S --noconfirm --needed glibc
yay -S --noconfirm --needed glibc-locales
yay -S --noconfirm --needed gparted
#yay -S --noconfirm --needed grim
yay -S --noconfirm --needed gtk-engine-murrine
yay -S --noconfirm --needed gtk-engines
yay -S --noconfirm --needed gvfs
yay -S --noconfirm --needed gvfs-afc
yay -S --noconfirm --needed gvfs-dnssd
yay -S --noconfirm --needed gvfs-mtp
yay -S --noconfirm --needed gvfs-nfs
yay -S --noconfirm --needed gvfs-smb
yay -S --noconfirm --needed gvfs-wsdd
yay -S --noconfirm --needed hypridle
yay -S --noconfirm --needed hyprland
yay -S --noconfirm --needed hyprland-protocols
yay -S --noconfirm --needed hyprlock
yay -S --noconfirm --needed hyprpicker
yay -S --noconfirm --needed hyprpolkitagent
yay -S --noconfirm --needed hyprshell
yay -S --noconfirm --needed hyprshot
yay -S --noconfirm --needed hyprsunset
yay -S --noconfirm --needed imagemagick
yay -S --noconfirm --needed impala
yay -S --noconfirm --needed imv
yay -S --noconfirm --needed inkscape
yay -S --noconfirm --needed inetutils
yay -S --noconfirm --needed jq
yay -S --noconfirm --needed kitty
yay -S --noconfirm --needed kitty-shell-integration
yay -S --noconfirm --needed kitty-terminfo
yay -S --noconfirm --needed kvantum
yay -S --noconfirm --needed less
yay -S --noconfirm --needed libqalculate
yay -S --noconfirm --needed libsixel
yay -S --noconfirm --needed luarocks
yay -S --noconfirm --needed luajit
#yay -S --noconfirm --needed slurp
yay -S --noconfirm --needed make
yay -S --noconfirm --needed man
yay -S --noconfirm --needed mpd
yay -S --noconfirm --needed meld
yay -S --noconfirm --needed most
yay -S --noconfirm --needed mpv
yay -S --noconfirm --needed nano
yay -S --noconfirm --needed neovim
yay -S --noconfirm --needed network-manager-applet
yay -S --noconfirm --needed networkmanager
yay -S --noconfirm --needed nm-connection-editor
yay -S --noconfirm --needed nfs-utils
yay -S --noconfirm --needed noto-fonts-emoji
yay -S --noconfirm --needed nwg-displays
#yay -S --noconfirm --needed nwg-dock-hyprland
yay -S --noconfirm --needed nwg-look
#yay -S --noconfirm --needed nwg-menu
yay -S --noconfirm --needed obs-studio
yay -S --noconfirm --needed obsidian
yay -S --noconfirm --needed openssh
yay -S --noconfirm --needed pacman-contrib
#yay -S --noconfirm --needed pamixer
yay -S --noconfirm --needed pavucontrol
yay -S --noconfirm --needed plocate
yay -S --noconfirm --needed power-profiles-daemon
#yay -S --noconfirm --needed pyprland
yay -S --noconfirm --needed qalculate-gtk
yay -S --noconfirm --needed qt5-wayland
yay -S --noconfirm --needed qt5ct
yay -S --noconfirm --needed qt6-wayland
yay -S --noconfirm --needed qt6ct
yay -S --noconfirm --needed ripgrep
yay -S --noconfirm --needed ripgrep-all
yay -S --noconfirm --needed rofi-wayland
yay -S --noconfirm --needed rustup
rustup install stable
yay -S --noconfirm --needed satty
yay -S --noconfirm --needed sddm
yay -S --noconfirm --needed starship
yay -S --noconfirm --needed sublime-text-4
yay -S --noconfirm --needed swaybg
yay -S --noconfirm --needed swaync
yay -S --noconfirm --needed swayosd
yay -S --noconfirm --needed swww
#yay -S --noconfirm --needed tela-circle-icon-theme-purple
yay -S --noconfirm --needed telegram-desktop
yay -S --noconfirm --needed terminus-font
yay -S --noconfirm --needed thunar
yay -S --noconfirm --needed thunar-archive-plugin
yay -S --noconfirm --needed thunar-media-tags-plugin
yay -S --noconfirm --needed thunar-shares-plugin
yay -S --noconfirm --needed thunar-vcs-plugin
yay -S --noconfirm --needed thunar-volman
yay -S --noconfirm --needed tldr
yay -S --noconfirm --needed tree-sitter-cli
yay -S --noconfirm --needed ttf-font-awesome
yay -S --noconfirm --needed ttf-fira-code
yay -S --noconfirm --needed ttf-firacode-nerd
yay -S --noconfirm --needed ttf-hack-nerd
yay -S --noconfirm --needed ttf-meslo-nerd 
yay -S --noconfirm --needed ttf-meslo-nerd-font-powerlevel10k
yay -S --noconfirm --needed ttf-terminus-nerd
yay -S --noconfirm --needed ttf-ubuntu-nerd
yay -S --noconfirm --needed tumbler
yay -S --noconfirm --needed unzip
#yay -S --noconfirm --needed uwsm
yay -S --noconfirm --needed walker
yay -S --noconfirm --needed waybar
yay -S --noconfirm --needed waybar-module-pacman-updates-git
yay -S --noconfirm --needed waypaper
yay -S --noconfirm --needed wget
yay -S --noconfirm --needed whois
yay -S --noconfirm --needed wlogout
yay -S --noconfirm --needed wttrbar
yay -S --noconfirm --needed xdg-desktop-portal-gtk
yay -S --noconfirm --needed xdg-desktop-portal-hyprland
yay -S --noconfirm --needed xdg-user-dirs-gtk
yay -S --noconfirm --needed xed
yay -S --noconfirm --needed xfce4-terminal
yay -S --noconfirm --needed xmlstarlet
yay -S --noconfirm --needed xournalpp
yay -S --noconfirm --needed yad
yay -S --noconfirm --needed zoxide
